jobs:
  android-aarch64-gpu1:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}
        submodules: true
    - name: sed Benchmark
      run: ' sed -i -e ''s?    benchmark(?//    benchmark(?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("squeezenet_int8"?    benchmark("squeezenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("mobilenet_int8"?    benchmark("mobilenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("resnet18_int8"?    benchmark("resnet18_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("googlenet_int8"?    benchmark("googlenet_int8"?''
        benchmark/benchncnn.cpp


        '
    - name: build
      run: 'mkdir build && cd build

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: build-shared
      run: 'mkdir build-shared && cd build-shared

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_SHARED_LIB=ON
        -DNCNN_ENABLE_LTO=ON ..

        cmake --build . -j 2

        '
    - name: build-termux
      run: 'mkdir build-termux && cd build-termux

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_PLATFORM_API=OFF
        ..

        cmake --build . -j 2

        '
    - name: build-android-29
      run: 'mkdir build-android-29 && cd build-android-29

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-29 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: Copy Network Param
      run: cp benchmark/*.param build-android-29/benchmark/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.time }}
        path: build-android-29/benchmark
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: 0f7e7bca0223bfa3600c08c808d2ded0a1cb3b04
          time: '2020-02-17'
        - sha: 2606d2a2c99c37d2c46768aaacb11030d306907e
          time: '2020-02-24'
        - sha: 4c5bdd7036add8decf494aff2700ff8a80f3c710
          time: '2020-03-01'
        - sha: 5be84ef76db4d00b67571351289eefc02f443bc2
          time: '2020-03-08'
        - sha: 8a84077429298dd7a55e2f2e96ded4204e0e955a
          time: '2020-03-15'
        - sha: d023137426691594bc17710d15065edc0d88f137
          time: '2020-03-20'
        - sha: 8fecf1989e342edef09a388ec925f1dd868e114e
          time: '2020-03-30'
        - sha: 85d5e5d3e45cb41822d55b3ee7055214ea63e879
          time: '2020-04-05'
        - sha: 956ab49d02d95a1343ed587b0d1b10529d281a10
          time: '2020-04-13'
        - sha: e49a9ec7366eaac2a19c872bbd3a57b15fa35ec6
          time: '2020-04-20'
        - sha: b2d9325c0dec51aafeceb077ff2fadf2510afc19
          time: '2020-04-23'
        - sha: bd55ddcf0dac927b0a07ac0f6fa5ad1ad6562149
          time: '2020-04-30'
        - sha: 803a4477f7ad5c6e83e022c704fe48ed0c740af0
          time: '2020-05-11'
        - sha: 72ac36ea6052a713cf29e6ca3cf5ce63c15a5e30
          time: '2020-05-18'
        - sha: cbdaf4b3e1dd11937ea4e269c13821b7c546abb7
          time: '2020-05-22'
        - sha: 765003a615d2ae65d978beda602433b61946c536
          time: '2020-06-01'
        - sha: c61a60bfc67fcc5d8cdce20ad2ab65ba19f2b6c8
          time: '2020-06-08'
        - sha: fd7d87e098db181da544c17fad4ce1fd72f8f639
          time: '2020-06-15'
        - sha: 71db6e1da500d517834c143a6b27437dd6da64cd
          time: '2020-06-22'
        - sha: ebce2c3742258388a3a56d18520a9214b6592c4e
          time: '2020-06-29'
  android-aarch64-gpu2:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}
        submodules: true
    - name: sed Benchmark
      run: ' sed -i -e ''s?    benchmark(?//    benchmark(?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("squeezenet_int8"?    benchmark("squeezenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("mobilenet_int8"?    benchmark("mobilenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("resnet18_int8"?    benchmark("resnet18_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("googlenet_int8"?    benchmark("googlenet_int8"?''
        benchmark/benchncnn.cpp


        '
    - name: build
      run: 'mkdir build && cd build

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: build-shared
      run: 'mkdir build-shared && cd build-shared

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_SHARED_LIB=ON
        -DNCNN_ENABLE_LTO=ON ..

        cmake --build . -j 2

        '
    - name: build-termux
      run: 'mkdir build-termux && cd build-termux

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_PLATFORM_API=OFF
        ..

        cmake --build . -j 2

        '
    - name: build-android-29
      run: 'mkdir build-android-29 && cd build-android-29

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-29 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: Copy Network Param
      run: cp benchmark/*.param build-android-29/benchmark/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.time }}
        path: build-android-29/benchmark
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: 8d984f105b1b8f816654ffa7719e96fbd5885971
          time: '2020-07-05'
        - sha: dd97ad36c1b75b4a871656be64bba44e623476ec
          time: '2020-07-11'
        - sha: 11cffce1146125a7d0136dcfa22d74fbe3d30997
          time: '2020-07-19'
        - sha: bedf00a5edf85ae8af33bc72ebd85fe325da1271
          time: '2020-07-27'
        - sha: 54e79a62d7aa063faaa8fab60893f7ec051d95cc
          time: '2020-08-02'
        - sha: 785b49aa87e9fdc1fc07b4000530a039da91cae7
          time: '2020-08-10'
        - sha: 952faf6668cdaf955d79e78f22b680af0245912a
          time: '2020-08-14'
        - sha: 1cb55454ebb93e9a6e43f5ce6978ccf721bff2d7
          time: '2020-08-23'
        - sha: 9f5b6604833f1edc85e2bfa1619685864f9a2679
          time: '2020-08-29'
        - sha: 8ec73408aecbec6cc28bb52ad87bd7c60a11a690
          time: '2020-09-07'
        - sha: 2c8288555cbbcc718b45d6c2263f770c7ea9ae06
          time: '2020-09-13'
        - sha: 8d56a62d5f55bdc58af881fdb7fcc3fbc4bdbcfb
          time: '2020-09-18'
        - sha: 7b5b829143ac2696a242ebab3eaa9272b310e28b
          time: '2020-09-24'
        - sha: 972bb4b52c9b4fa6a5b937224e55fa4f904f8ed6
          time: '2020-09-29'
        - sha: 9be3f074a9f65c5420b2b0466c4aa9dc1d3d22f6
          time: '2020-10-11'
        - sha: a8f38f61706d8fad3d5ad75f7fcba7ba72a3bc64
          time: '2020-10-16'
        - sha: 799643f07b6d4657c35d4ab38eb5429c7be3511d
          time: '2020-10-26'
        - sha: a742979fea8885e067a8454b6fbb099e99f35c34
          time: '2020-10-30'
        - sha: b3bbc1b8e912316fbd93c631378b7b2fcff374d1
          time: '2020-11-09'
        - sha: b441f738bd23b2d0331f797775f2d8a7a3219f93
          time: '2020-11-16'
  android-aarch64-gpu3:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}
        submodules: true
    - name: sed Benchmark
      run: ' sed -i -e ''s?    benchmark(?//    benchmark(?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("squeezenet_int8"?    benchmark("squeezenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("mobilenet_int8"?    benchmark("mobilenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("resnet18_int8"?    benchmark("resnet18_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("googlenet_int8"?    benchmark("googlenet_int8"?''
        benchmark/benchncnn.cpp


        '
    - name: build
      run: 'mkdir build && cd build

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: build-shared
      run: 'mkdir build-shared && cd build-shared

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_SHARED_LIB=ON
        -DNCNN_ENABLE_LTO=ON ..

        cmake --build . -j 2

        '
    - name: build-termux
      run: 'mkdir build-termux && cd build-termux

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_PLATFORM_API=OFF
        ..

        cmake --build . -j 2

        '
    - name: build-android-29
      run: 'mkdir build-android-29 && cd build-android-29

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-29 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: Copy Network Param
      run: cp benchmark/*.param build-android-29/benchmark/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.time }}
        path: build-android-29/benchmark
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: 1184404fbf78c55b27358cf3184906883ca2444f
          time: '2020-11-22'
        - sha: 14ba69803452b7626a473e668c699c034b5081b0
          time: '2020-11-30'
        - sha: 73319905989d63ee61f094b6e38d0a1beb4af4c1
          time: '2020-12-06'
        - sha: 5f539beea550636b6e3966fd3c909b2db0659faa
          time: '2020-12-13'
        - sha: a9df4f6c59be70b85e16a7aa3461ae9cbb8dbea4
          time: '2020-12-21'
        - sha: 25506cfba0f5a17d29809190b27878f1802bce74
          time: '2020-12-26'
        - sha: ce7ac39a96ab525a9a2177e01049e2e680c4e465
          time: '2021-01-03'
        - sha: fca04980f3a58e14cfb61cf398c932e84a2fc0fd
          time: '2021-01-11'
        - sha: af7d8184aa260a385328166a8e0c5c720fd1b9bb
          time: '2021-01-17'
        - sha: 73fb3b583f11caa6a3a58d2b941d8bc1f3b59a20
          time: '2021-01-25'
        - sha: 18980d717e3a35bf5f80ec3bd8662269632ed943
          time: '2021-01-31'
        - sha: ab56083ca543d4315bef9913b23b843e1fdd8c76
          time: '2021-02-06'
        - sha: 9fd4d371ae03a70a73162ecde624c7feb8c0a82b
          time: '2021-02-10'
        - sha: 41fba71fa0dfaa62a263cb96a3ae57f2f35650e8
          time: '2021-02-22'
        - sha: 57397c418d7198fa3507236d12dbe47b452aee35
          time: '2021-03-01'
        - sha: 2d31868389f7e8fb37cac73a072beefa8cfaeaa0
          time: '2021-03-06'
        - sha: f5b307689b4c98d28513d6e9fd8d78de20f0db96
          time: '2021-03-13'
        - sha: 5f00ba89d25a427e492fb4b23befa61c04220afe
          time: '2021-03-22'
        - sha: 8011aea8c8c2b2905bd5c9477681e566818f5c74
          time: '2021-03-29'
        - sha: cc8e7a13faa64e108d09eada1e58b0c6238d2e3c
          time: '2021-04-02'
  android-aarch64-gpu4:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}
        submodules: true
    - name: sed Benchmark
      run: ' sed -i -e ''s?    benchmark(?//    benchmark(?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("squeezenet_int8"?    benchmark("squeezenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("mobilenet_int8"?    benchmark("mobilenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("resnet18_int8"?    benchmark("resnet18_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("googlenet_int8"?    benchmark("googlenet_int8"?''
        benchmark/benchncnn.cpp


        '
    - name: build
      run: 'mkdir build && cd build

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: build-shared
      run: 'mkdir build-shared && cd build-shared

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_SHARED_LIB=ON
        -DNCNN_ENABLE_LTO=ON ..

        cmake --build . -j 2

        '
    - name: build-termux
      run: 'mkdir build-termux && cd build-termux

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_PLATFORM_API=OFF
        ..

        cmake --build . -j 2

        '
    - name: build-android-29
      run: 'mkdir build-android-29 && cd build-android-29

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-29 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: Copy Network Param
      run: cp benchmark/*.param build-android-29/benchmark/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.time }}
        path: build-android-29/benchmark
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: bd994ddba3cd3dddc6ba8237c886d68cc4715159
          time: '2021-04-12'
        - sha: 478b8f072e18a3a5a94e03343fe15143d6127518
          time: '2021-04-18'
        - sha: f9e42d4ee4bac064494b05752bd10540786de3f6
          time: '2021-04-26'
        - sha: 37aeba236959d45b03333d0293cd99d31aa585f5
          time: '2021-05-02'
        - sha: da40cc6ec8174f230490b47f5c7e9b572892350f
          time: '2021-05-09'
        - sha: 5f62fdec8703e9340ac77bcb97d04e05c46c527e
          time: '2021-05-16'
        - sha: 26ea87cc25fed27791d8d89fd8c7ce82b7544486
          time: '2021-05-24'
        - sha: 71bc617a05f073d8b623dcc95e88eb5e1eb16aa5
          time: '2021-05-29'
        - sha: ccc597740f8095145cac611d0e6763923f25c006
          time: '2021-06-03'
        - sha: 08f285772e8729836197b44db741e9f61182d6d5
          time: '2021-06-12'
        - sha: c1ce8ea84d55b9e223025bb5e3b8a9d978f1205d
          time: '2021-06-19'
        - sha: 64092d0c7cd47aa384235677c86a048e513d095e
          time: '2021-06-27'
        - sha: 90b38ba1454af0ecc46f94aeef7d6886cf97bf7a
          time: '2021-07-04'
        - sha: 5049aaeabd3e36ad4131ad46da3ecd12c973eea6
          time: '2021-07-11'
        - sha: dba7348f1753b8e96cd8805aaaebaa2881adc11a
          time: '2021-07-18'
        - sha: 618f0f70ac273e0c9ad52d28ead4a5fa4f905909
          time: '2021-07-26'
        - sha: ba8e81453932ed946fcbad1f445b36b3f1bf47bd
          time: '2021-08-02'
        - sha: a6667ee6c48ca591fd33aa98134e8ecefba4fc19
          time: '2021-08-06'
        - sha: ec561736a5ca4f3853c2b48319efb2bb77b82889
          time: '2021-08-12'
        - sha: c44a6c7f47087222ffb0c9475fc49fdb66e6b62b
          time: '2021-08-23'
  android-aarch64-gpu5:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}
        submodules: true
    - name: sed Benchmark
      run: ' sed -i -e ''s?    benchmark(?//    benchmark(?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("squeezenet_int8"?    benchmark("squeezenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("mobilenet_int8"?    benchmark("mobilenet_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("resnet18_int8"?    benchmark("resnet18_int8"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("googlenet_int8"?    benchmark("googlenet_int8"?''
        benchmark/benchncnn.cpp


        '
    - name: build
      run: 'mkdir build && cd build

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: build-shared
      run: 'mkdir build-shared && cd build-shared

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_SHARED_LIB=ON
        -DNCNN_ENABLE_LTO=ON ..

        cmake --build . -j 2

        '
    - name: build-termux
      run: 'mkdir build-termux && cd build-termux

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=OFF -DNCNN_PLATFORM_API=OFF
        ..

        cmake --build . -j 2

        '
    - name: build-android-29
      run: 'mkdir build-android-29 && cd build-android-29

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-29 -DNCNN_VULKAN=OFF ..

        cmake --build . -j 2

        '
    - name: Copy Network Param
      run: cp benchmark/*.param build-android-29/benchmark/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.time }}
        path: build-android-29/benchmark
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: 41aa6014135fa39a7b8297dfed4054544b6535d0
          time: '2021-08-23'
name: android-armv8-gpu
'on':
  watch:
    types:
    - started
  workflow_dispatch: null

