jobs:
  android-aarch64-gpu0:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}
        submodules: true
    - name: sed Benchmark
      run: ' sed -i -e ''s?//    benchmark("mobilenet"?    benchmark("mobilenet"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("googlenet"?    benchmark("googlenet"?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("shufflenet"?    benchmark("shufflenet"?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("squeezenet"?    benchmark("squeezenet"?'' benchmark/benchncnn.cpp

        '
    - name: build
      run: 'mkdir build && cd build

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..

        cmake --build . -j 2

        '
    - name: build-shared
      run: 'mkdir build-shared && cd build-shared

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON -DNCNN_SHARED_LIB=ON
        -DNCNN_ENABLE_LTO=ON ..

        cmake --build . -j 2

        '
    - name: build-termux
      run: 'mkdir build-termux && cd build-termux

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON -DNCNN_PLATFORM_API=OFF
        ..

        cmake --build . -j 2

        '
    - name: build-android-29
      run: 'mkdir build-android-29 && cd build-android-29

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-29 -DNCNN_VULKAN=ON ..

        cmake --build . -j 2

        '
    - name: Copy Network Param
      run: cp benchmark/*.param build-android-29/benchmark/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.time }}
        path: build-android-29/benchmark
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: 30ff3800d80f91cf1f966a2f42583484f451a3b7
          time: 2020-08-12T03_44_25Z
        - sha: 62c453b16d07a851cc44881a557ef18850550846
          time: 2020-08-11T06_48_17Z
        - sha: b5b486fbfa1bbd7d0722802de014871cce1448e1
          time: 2020-08-10T09_29_28Z
        - sha: 785b49aa87e9fdc1fc07b4000530a039da91cae7
          time: 2020-08-10T06_22_07Z
        - sha: 418047661ca09b2ab7eb4e47e6810e5e15ce0484
          time: 2020-08-09T06_20_43Z
        - sha: e2557c16785e98349e50bcc1f4c21a9d5055c612
          time: 2020-08-07T08_04_18Z
        - sha: 5a9c99ce004f56dcf611392f76f5874f96b779e5
          time: 2020-08-06T15_28_33Z
        - sha: e841ae73c6f1282c365be84f226bfff56c37c367
          time: 2020-08-06T04_45_43Z
        - sha: 8df3a023911cf8fd5012219b774c471bf73396ed
          time: 2020-08-06T04_31_01Z
        - sha: d8e9fc14433ceab36876f31853a16b972714f40d
          time: 2020-08-05T15_48_46Z
        - sha: 076b509bb9af626f2076262e8d94230f5bb05ab1
          time: 2020-08-05T09_46_47Z
        - sha: ef5bacc12d0cac64faf2375d400f7e800ecdb546
          time: 2020-08-05T09_37_55Z
        - sha: ac9cbaca564bfcaf6fb38a57e749ddc9229fde4f
          time: 2020-08-05T09_26_35Z
        - sha: b53f4072ce0e6d368f64c8b8618370473c1657f1
          time: 2020-08-05T07_52_12Z
        - sha: f6d808b0903bee60a53a18cc706f4b56e4b850f8
          time: 2020-08-05T05_14_44Z
        - sha: bc05a71a7c1089e658e7b3653a52207f5fe032eb
          time: 2020-08-05T03_48_00Z
        - sha: 5d5a3d1434408bec386b755ac2490962493a4e8a
          time: 2020-08-04T12_05_41Z
        - sha: 20a0fc8628e21909b7780c95eb181cc9ef4f7a2d
          time: 2020-08-03T10_32_43Z
        - sha: 54e79a62d7aa063faaa8fab60893f7ec051d95cc
          time: 2020-08-02T14_44_14Z
        - sha: c173d51c9b3278900be9b8e112091625f2a05cd8
          time: 2020-08-02T08_23_18Z
  android-aarch64-gpu1:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}
        submodules: true
    - name: sed Benchmark
      run: ' sed -i -e ''s?//    benchmark("mobilenet"?    benchmark("mobilenet"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("googlenet"?    benchmark("googlenet"?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("shufflenet"?    benchmark("shufflenet"?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("squeezenet"?    benchmark("squeezenet"?'' benchmark/benchncnn.cpp

        '
    - name: build
      run: 'mkdir build && cd build

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..

        cmake --build . -j 2

        '
    - name: build-shared
      run: 'mkdir build-shared && cd build-shared

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON -DNCNN_SHARED_LIB=ON
        -DNCNN_ENABLE_LTO=ON ..

        cmake --build . -j 2

        '
    - name: build-termux
      run: 'mkdir build-termux && cd build-termux

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON -DNCNN_PLATFORM_API=OFF
        ..

        cmake --build . -j 2

        '
    - name: build-android-29
      run: 'mkdir build-android-29 && cd build-android-29

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-29 -DNCNN_VULKAN=ON ..

        cmake --build . -j 2

        '
    - name: Copy Network Param
      run: cp benchmark/*.param build-android-29/benchmark/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.time }}
        path: build-android-29/benchmark
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: 72a27d4776efca15023a324c17721ee04f3f9401
          time: 2020-08-02T03_52_02Z
        - sha: e644164873b98c0a6173517cd216ce794e877e91
          time: 2020-07-31T08_43_36Z
        - sha: aa68246dc770a6a06a91a19f6258b1d1dc88cf8c
          time: 2020-07-31T05_07_15Z
        - sha: e7abc5fbd7a8db41b8ccb95d66d0dad155114aa3
          time: 2020-07-31T03_37_28Z
        - sha: aa1a9e90c571fbf3e2bf58a6c622e9aa099876f0
          time: 2020-07-30T16_42_02Z
        - sha: df5a7f32d4ef65057ed07bb1aaecc387c247ff06
          time: 2020-07-30T10_56_13Z
        - sha: c6d7525367a4e66063bf82cce050d04ec60cb3ae
          time: 2020-07-30T10_49_24Z
        - sha: bc3822acc37ecc23845f83668f2cc237c5da8153
          time: 2020-07-30T08_49_06Z
        - sha: dbb761b9a4401740f41c337add556f6b7662005c
          time: 2020-07-30T06_52_08Z
        - sha: 91d91ba5560a7384254495b5483caca77e0ef4d7
          time: 2020-07-30T03_03_48Z
        - sha: 7b1cfd5b04b68505163cf42b5539589f030a41e2
          time: 2020-07-29T11_13_24Z
        - sha: f23122bb3f19a73e01b89fae7887c297bd12fa50
          time: 2020-07-29T09_03_57Z
        - sha: a18a9fd8c5c8f4d4ffa929692754c0a7f528c3dd
          time: 2020-07-29T07_38_13Z
        - sha: 8385d81afad090f6b48a99076725d11370d57eec
          time: 2020-07-29T06_59_02Z
        - sha: 5a4243e44e07e80022d5d326a3081650b3239bc6
          time: 2020-07-29T03_45_46Z
        - sha: 301abe657ccba21f4b29222cfb7551034b8ea53c
          time: 2020-07-29T02_49_25Z
        - sha: 03c9ed11d269862ffae25b21192eba5a0ae3085b
          time: 2020-07-28T16_15_33Z
        - sha: 71f86af8a680f910c2ecc067aa5e772e1db47f6c
          time: 2020-07-28T14_51_29Z
        - sha: 9a2e2a693714cea8e6ed1946708eb805818ce208
          time: 2020-07-28T14_36_21Z
        - sha: d4d501a7fe87b568ba9f40c35e9d75dd7a026af0
          time: 2020-07-28T14_14_07Z
  android-aarch64-gpu2:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}
        submodules: true
    - name: sed Benchmark
      run: ' sed -i -e ''s?//    benchmark("mobilenet"?    benchmark("mobilenet"?''
        benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("googlenet"?    benchmark("googlenet"?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("shufflenet"?    benchmark("shufflenet"?'' benchmark/benchncnn.cpp

        sed -i -e ''s?//    benchmark("squeezenet"?    benchmark("squeezenet"?'' benchmark/benchncnn.cpp

        '
    - name: build
      run: 'mkdir build && cd build

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON ..

        cmake --build . -j 2

        '
    - name: build-shared
      run: 'mkdir build-shared && cd build-shared

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON -DNCNN_SHARED_LIB=ON
        -DNCNN_ENABLE_LTO=ON ..

        cmake --build . -j 2

        '
    - name: build-termux
      run: 'mkdir build-termux && cd build-termux

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-24 -DNCNN_VULKAN=ON -DNCNN_PLATFORM_API=OFF
        ..

        cmake --build . -j 2

        '
    - name: build-android-29
      run: 'mkdir build-android-29 && cd build-android-29

        cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake
        -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-29 -DNCNN_VULKAN=ON ..

        cmake --build . -j 2

        '
    - name: Copy Network Param
      run: cp benchmark/*.param build-android-29/benchmark/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.time }}
        path: build-android-29/benchmark
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: e9c71a1eadeb1f1d9b1be343940a9148e51f76b2
          time: 2020-07-28T14_06_38Z
        - sha: 1a57600bd7e533631f9878f4c2c432703322ee9f
          time: 2020-07-28T13_37_20Z
        - sha: 11f5033249b276db39fff3da003a3f78d13cb848
          time: 2020-07-28T12_11_06Z
        - sha: 6ab284bc3ad28e51dc2c373c53dcc81be9a8804d
          time: 2020-07-28T10_53_20Z
        - sha: 6d2c0e5683d65b0a4ae3014a84c00922926e2c33
          time: 2020-07-28T06_28_53Z
        - sha: 47ae0c151a7803fdf790e23b7ee705d6d88a5c14
          time: 2020-07-28T06_24_49Z
        - sha: 01d9ebf115a15ba2e2cc7cfe7bfe1f31e70ae426
          time: 2020-07-28T02_50_37Z
        - sha: 7d2c3247bc022dd983f0ceabfc933469b2daad60
          time: 2020-07-27T16_32_41Z
        - sha: b80b84fda51c02bbf5b12030a0b66fea65fbb94e
          time: 2020-07-27T10_39_39Z
name: android-armv8-gpu
on:
    workflow_dispatch:

